# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{juggernaut_rails}
  s.version = "0.6.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex MacCaw"]
  s.date = %q{2010-05-10}
  s.default_executable = %q{juggernaut}
  s.description = %q{      The Juggernaut Gem for Ruby on Rails aims to revolutionize your Rails app by letting the server initiate a connection and push data to the client. In other words your app can have a real time connection to the server with the advantage of instant updates. Although the obvious use of this is for chat, the most exciting prospect for me is collaborative cms and wikis.
      
      This Gem bundles Alex MacCaw's Juggernaut Gem and Rails plugin into one, and extends its Rails intergration for a simpler install and setup.
}
  s.email = %q{info@eribium.org}
  s.executables = ["juggernaut"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/juggernaut",
     "lib/juggernaut.rb",
     "lib/juggernaut/client.rb",
     "lib/juggernaut/message.rb",
     "lib/juggernaut/miscel.rb",
     "lib/juggernaut/rails.rb",
     "lib/juggernaut/rails/convenience_methods.rb",
     "lib/juggernaut/rails/helpers.rb",
     "lib/juggernaut/rails/render_extension.rb",
     "lib/juggernaut/rails/tasks.rb",
     "lib/juggernaut/runner.rb",
     "lib/juggernaut/server.rb",
     "lib/juggernaut/utils.rb",
     "lib/juggernaut_rails.rb",
     "media/expressinstall.swf",
     "media/jquery.js",
     "media/jquerynaut.js",
     "media/json.js",
     "media/juggernaut.as",
     "media/juggernaut.js",
     "media/juggernaut.swf",
     "media/juggernaut.yml",
     "media/juggernaut_hosts.yml",
     "media/log/juggernaut.log",
     "media/swfobject.js",
     "rails/init.rb",
     "test/test_client.rb",
     "test/test_juggernaut.rb",
     "test/test_message.rb",
     "test/test_runner.rb",
     "test/test_server.rb",
     "test/test_utils.rb"
  ]
  s.homepage = %q{http://juggernaut.rubyforge.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib", "lib/juggernaut"]
  s.rubyforge_project = %q{juggernaut}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A push server written in Ruby with Rails integration.}
  s.test_files = [
    "test/test_client.rb",
     "test/test_juggernaut.rb",
     "test/test_message.rb",
     "test/test_runner.rb",
     "test/test_server.rb",
     "test/test_utils.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.10.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.1.2"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.10.0"])
      s.add_dependency(%q<json>, [">= 1.1.2"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.10.0"])
    s.add_dependency(%q<json>, [">= 1.1.2"])
  end
end

